### ISSUE TITLE
dll error

### ISSUE THREAD

**Issue by kashmir2003** [vinz9/DistThresholdCHOP#1]
Hello i always get a dll cont load error, should i put it in some special place ?

**Comment by vinz9** [comment]
The dll goes either in a Plugins folder where the toe file is (just learned that recently, one day I’ll repackage the release zip file), or in a Plugins folder inside the Derivative folder in Documents.
See https://wiki.derivative.ca/Custom_Operators#Using_Custom_OPs_-_Plugin_Folder_Locations
